project_id = "factact"

[api]
enabled = false
port = 54321
schemas = ["public"]

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = false

[auth]
enabled = false

[storage]
enabled = false

[realtime]
enabled = false

[analytics]
enabled = false
