import {useEffect,useState} from 'react';
import type {Operator} from '../../../../packages/domain/src/operator.js';
import type {SupportListView,SupportDetailView} from '../../../../packages/application/src/support-queries.js';
import {api} from './api.js';
type Props={csrf:string;operator:Operator;revision:number;busy:boolean;run:(fn:()=>Promise<void>)=>Promise<void>;id?:string};
function useRead<T>(url:string,revision:number){const [data,setData]=useState<T|null>(null),[error,setError]=useState('');useEffect(()=>{let active=true;api<T>(url).then(x=>{if(active){setData(x);setError('');}}).catch(()=>{if(active)setError('問い合わせ情報を取得できませんでした。再読み込みしてください。');});return()=>{active=false;};},[url,revision]);return{data,error};}
export function SupportTasks({operator,revision}:{operator:Operator;revision:number}){const {data}=useRead<SupportListView>('/api/support',revision);return <>{data?.inquiries.filter(x=>x.work&&x.work.status!=='COMPLETED'&&x.work.workOwnerOperatorId===operator.id).map(x=><article key={x.event.id}><p>あなたの担当 / 問い合わせ</p><a href={`#/support/${x.event.id}`}>{x.person.displayName}さんのVPN接続の問い合わせ</a><p>次にやること: {x.work?.nextAction}</p></article>)}</>;}
const auditLabels:Record<string,string>={SUPPORT_RECEIVED:'本人からの問い合わせを受付',SUPPORT_EVALUATED:'対応の必要性と担当を確認',SUPPORT_GUIDANCE_RECORDED:'確認・判断・案内の実施を記録',SUPPORT_KNOWLEDGE_SAVED:'次の対応への参考知識を保存',SUPPORT_COMPLETED:'問い合わせ対応を完了'};
export function SupportUI(props:Props){return props.id?<SupportDetail key={props.id} {...props} id={props.id}/>:<SupportList {...props}/>;}
function SupportList({csrf,operator,revision,busy,run}:Props){const {data:v,error}=useRead<SupportListView>('/api/support',revision);const [requestId]=useState(()=>crypto.randomUUID());if(error)return <p role="alert">{error}</p>;if(!v)return <p>確認しています…</p>;return <><h1>問い合わせ対応</h1><p>確認済みの利用状況を使って、必要な確認と案内を行います。</p><section className="card"><h2>問い合わせを受け付ける</h2><p>申告を記録します。対応が必要かを確認するまでは、作業は開始しません。</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const event=await api<{id:string}>('/api/support',csrf,{requestId,personId:f.get('personId'),serviceId:f.get('serviceId'),symptom:f.get('symptom')});location.hash=`/support/${event.id}`;});}}><label htmlFor="support-person">問い合わせ元</label><select id="support-person" name="personId">{v.people.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><label htmlFor="support-service">対応サービス</label><select id="support-service" name="serviceId">{v.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><label>本人からの申告<textarea name="symptom" required maxLength={4000} placeholder="例: 会社PCでVPNにつながりません"/></label><p>申告は本人から聞いた内容として保存します。技術的な障害が確認済みになるわけではありません。</p><button disabled={busy||!v.people.length||!operator.roles.some(r=>r==='ADMIN'||r==='OPERATOR')}>問い合わせを記録</button></form></section><h2>受け付けた問い合わせ</h2>{v.inquiries.map(x=><article key={x.event.id}><a href={`#/support/${x.event.id}`}>{x.person.displayName}さんの問い合わせ</a><p>{x.work?x.work.status==='COMPLETED'?'対応完了':x.work.workOwnerOperatorId===operator.id?'あなたの担当です':'担当者あり':'対応の必要性を未確認'}</p></article>)}</>;}
function SupportDetail({id,csrf,operator,revision,busy,run}:Props&{id:string}){const {data:v,error}=useRead<SupportDetailView>(`/api/support/${id}`,revision);if(error)return <p role="alert">{error}</p>;if(!v)return <p>確認しています…</p>;const w=v.work,allowed=operator.roles.some(r=>v.executeRoles.includes(r))&&operator.roles.some(r=>r==='ADMIN'||r==='OPERATOR');return <><h1>{v.person.displayName}さんからの問い合わせ</h1><div className="workspace"><section>
  <p>受付: {new Date(v.event.createdAt).toLocaleString('ja-JP')}</p><article className="notice" aria-label="本人からの申告"><h2>本人からの申告</h2><p>{v.observation.contentText}</p><p>本人から聞いた内容です。技術的な障害として確認済みではありません。</p><details><summary>申告の出典</summary><p>問い合わせ元: {v.person.displayName}</p><p>記録日時: {new Date(v.observation.observedAt).toLocaleString('ja-JP')}</p><p>OBSERVATION / UNVERIFIED</p></details></article>
  {!v.evaluation&&<section className="card"><h2>対応の必要性を確認</h2><p>まだ担当する作業は作成されていません。必要と判断した場合、あなたを担当として確認・案内の対応を作成します。</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api(`/api/support/${id}/evaluate`,csrf,{decision:f.get('decision'),reason:f.get('reason')});});}}><label htmlFor="triage-decision">必要な対応</label><select id="triage-decision" name="decision"><option value="REQUIRED">確認・案内が必要</option><option value="NOT_APPLICABLE">このサービスでの対応は不要</option></select><label>対応が必要・不要と判断した理由<textarea name="reason" required maxLength={4000}/></label><button disabled={busy||!allowed}>対応の必要性と担当を記録</button></form></section>}
  {v.evaluation&&!w&&<article><h2>対応は作成していません</h2><p>受付時の判断: {v.evaluation.basisSummary}</p><p>調査してから追加対応が不要と分かったケースとは区別して記録しています。</p></article>}
  {w&&<><section className="ownership"><p className="badge">{w.workOwnerOperatorId===operator.id?'あなたの担当です':'他の担当者の対応です'}</p><p>担当: {v.owner?.displayName??'未確認'}</p><p>担当になった理由: 対応が必要と確認した担当者として登録されています。</p><p>問い合わせ元: {v.person.displayName}</p></section><section className="next-action"><h2>次にやること</h2><p className="next-title">{w.nextAction}</p><h3>なぜこの確認が必要？</h3><p>{v.evaluation?.basisSummary}</p><p>利用PCの登録があっても、VPNの利用対象か、申告された症状の原因は分かりません。契約の担当窓口と本人に根拠を確認してください。</p></section>
  <section><h2>確認手順</h2><details><summary>VPN接続トラブルの一次切り分けを見る</summary><p>同梱デモ手順 / support-demo-v1 — 実環境の承認済み手順ではありません。</p><ol><li>確認済みの利用PCと今回の申告を分けて確認する。既知のPCを再入力しない。</li><li>契約の担当窓口へVPN利用対象かを確認し、根拠を記録する。</li><li>本人へ発生時刻・エラー内容・他ネットワークでの再現を確認する。分からない場合は未確認のまま扱う。</li><li>確認根拠に基づき、案内するか追加対応が不要かを判断する。</li><li>既知の接続手順を案内する。機器・設定の変更が必要ならこの画面で完了扱いにせず、別途検証・正式反映を伴う対応を依頼する。</li></ol><p>パスワード・認証コードは記録しないでください。</p></details><details><summary>VPN接続時によくある確認ポイント</summary><p>同梱デモの参考知識。利用PCを持つことだけではVPN利用資格は分かりません。申告と実際の確認結果を混同しないでください。</p></details></section>
  {!v.decision&&<form className="card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api(`/api/support-work/${w.id}/resolution`,csrf,{mode:f.get('mode'),diagnosticEvidence:f.get('diagnosticEvidence'),rationale:f.get('rationale'),actionSummary:f.get('actionSummary')});});}}><h2>確認結果と実施内容を記録</h2><p>この画面は調査・案内専用です。利用PCやVPN設定の管理情報は変更しません。</p><label>確認した内容と根拠<textarea name="diagnosticEvidence" required maxLength={4000}/></label><label htmlFor="support-mode">今回の判断</label><select id="support-mode" name="mode"><option value="GUIDANCE_ONLY">根拠を確認して接続手順を案内した</option><option value="NO_ACTION_REQUIRED">調査の結果、追加対応は不要だった</option></select><label>その判断をした理由<textarea name="rationale" required maxLength={4000}/></label><label>実際に行った調査・案内<textarea name="actionSummary" required maxLength={4000}/></label><button disabled={busy||!allowed}>確認・判断・案内の実施を記録</button></form>}
  {v.decision&&<><article><h2>確認・案内の実施記録</h2><p>確認根拠: {v.evidence?.contentText}</p><p>今回の判断: {v.decision.rationale}</p><p>実施内容: {v.action?.resultSummary}</p><p>管理情報の変更: ありません。利用PC・VPN設定を変更した記録ではありません。</p><p>技術的な問題が解消したという自動判定は行いません。</p><p>VPN利用要否などの恒久的な管理情報は未確認のままです。今回確認した範囲は上の根拠・判断として残します。</p></article>
  {!v.knowledge&&<form className="card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api(`/api/support-work/${w.id}/knowledge`,csrf,{title:f.get('title'),content:f.get('content')});});}}><h2>次の対応に役立つことを残す</h2><p>このサービスの今後の問い合わせに参考知識の候補として表示します。承認済みルールにはなりません。個人情報を含めず、適用条件と限界を記してください。</p><label>参考知識の見出し<input name="title" required maxLength={200}/></label><label>役立った内容・適用条件・限界<textarea name="content" required maxLength={4000}/></label><button disabled={busy||!allowed}>参考知識の候補を保存</button></form>}
  {w.status!=='COMPLETED'&&<><p>完了として残す内容: {v.decision.mode==='GUIDANCE_ONLY'?'確認・案内を実施した対応':'調査した結果、追加対応が不要だった対応'}。利用PCの管理情報は変更しません。</p><button disabled={busy||!allowed} onClick={()=>void run(async()=>{await api(`/api/support-work/${w.id}/complete`,csrf,{});})}>問い合わせ対応を完了</button></>}
  </>}
  {w.status==='COMPLETED'&&<p role="status">{w.outcome==='NO_ACTION_REQUIRED'?'調査完了・追加対応不要':'確認・案内の対応を完了しました'}</p>}</>}
  <section><h2>次の対応に再利用できる参考知識</h2>{!v.relatedKnowledge.length&&<p>このサービスで記録した候補はまだありません。</p>}{v.relatedKnowledge.map(k=><article key={k.id}><h3>{k.title}</h3><p>参考知識の候補 / 未承認 — 適用ルールではありません</p><p>{k.contentText}</p><details><summary>元の対応・確認根拠</summary><p>Work: {k.sourceWorkId}</p><p>Evidence: {k.sourceEvidenceId}</p><p>Decision: {k.sourceDecisionId}</p></details></article>)}</section>
  </section><aside aria-label="確認済みの現在の利用状況"><h2>確認済みの現在の利用状況</h2>{v.deviceFact?<div className="fact"><h3>利用PC: {v.deviceFact.device.assetTag}</h3><p>確認済み</p><p>入社PC準備で確認された利用PC情報を参照しています。問い合わせ用のコピーではありません。</p><p>確認日時: {new Date(v.deviceFact.relation.verifiedAt).toLocaleString('ja-JP')}</p><a href={`#/people/${v.person.id}`}>対象者の現在の利用状況</a><details><summary>利用PCの確認元</summary><a href={`#/work/${v.deviceFact.sourceChange.workId}`}>PC準備の実施・確認履歴</a><p>Relation: {v.deviceFact.relation.id}</p><p>Source Change: {v.deviceFact.relation.sourceChangeId}</p></details></div>:<p className="unknown">利用PC: 未確認。本人・端末の担当窓口に確認してください。</p>}<h3>まだ未確認の管理情報</h3><ul>{v.unknowns.map(s=><li key={s}>{s}: 未確認</li>)}</ul><p>調査結果は今回の確認根拠として残ります。この一覧が自動で確認済みになることはありません。</p></aside></div><section aria-label="問い合わせの対応履歴"><h2>対応履歴</h2><ol>{v.timeline.map(e=><li key={e.id}>{auditLabels[e.eventType]??'関連する記録'}<details><summary>監査用の詳細</summary><pre>{JSON.stringify(e.metadataJson,null,2)}</pre></details></li>)}</ol></section></>;}
