import {SupportDetail} from './support-wizard.js';
import {useEffect,useState} from 'react';
import type {Operator} from '../../../../packages/domain/src/operator.js';
import type {SupportListView,SupportDetailView} from '../../../../packages/application/src/support-queries.js';
import {api} from './api.js';
export type Props={csrf:string;operator:Operator;revision:number;busy:boolean;run:(fn:()=>Promise<void>)=>Promise<void>;id?:string};
export function useRead<T>(url:string,revision:number){const [data,setData]=useState<T|null>(null),[error,setError]=useState('');useEffect(()=>{let active=true;api<T>(url).then(x=>{if(active){setData(x);setError('');}}).catch(()=>{if(active)setError('問い合わせ情報を取得できませんでした。再読み込みしてください。');});return()=>{active=false;};},[url,revision]);return{data,error};}
export function SupportTasks({operator,revision}:{operator:Operator;revision:number}){const {data}=useRead<SupportListView>('/api/support',revision);return <>{data?.inquiries.filter(x=>x.work&&x.work.status!=='COMPLETED'&&x.work.workOwnerOperatorId===operator.id).map(x=><article key={x.event.id}><p>あなたの担当 / 問い合わせ</p><a href={`#/support/${x.event.id}`}>{x.person.displayName}さんのVPN接続の問い合わせ</a><p>次にやること: {x.work?.nextAction}</p></article>)}</>;}
export const auditLabels:Record<string,string>={SUPPORT_RECEIVED:'本人からの問い合わせを受付',SUPPORT_EVALUATED:'対応の必要性と担当を確認',SUPPORT_GUIDANCE_RECORDED:'確認・判断・案内の実施を記録',SUPPORT_KNOWLEDGE_SAVED:'次の対応への参考知識を保存',SUPPORT_COMPLETED:'問い合わせ対応を完了'};
export function SupportUI(props:Props){return props.id?<SupportDetail key={props.id} {...props} id={props.id}/>:<SupportList {...props}/>;}
function SupportList({csrf,operator,revision,busy,run}:Props){const {data:v,error}=useRead<SupportListView>('/api/support',revision);const [requestId]=useState(()=>crypto.randomUUID());if(error)return <p role="alert">{error}</p>;if(!v)return <p>確認しています…</p>;return <><h1>問い合わせ対応</h1><p>確認済みの利用状況を使って、必要な確認と案内を行います。</p><section className="card"><h2>問い合わせを受け付ける</h2><p>申告を記録します。対応が必要かを確認するまでは、作業は開始しません。</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const event=await api<{id:string}>('/api/support',csrf,{requestId,personId:f.get('personId'),serviceId:f.get('serviceId'),symptom:f.get('symptom')});location.hash=`/support/${event.id}`;});}}><label htmlFor="support-person">問い合わせ元</label><select id="support-person" name="personId">{v.people.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><label htmlFor="support-service">対応サービス</label><select id="support-service" name="serviceId">{v.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><label>本人からの申告<textarea name="symptom" required maxLength={4000} placeholder="例: 会社PCでVPNにつながりません"/></label><p>申告は本人から聞いた内容として保存します。技術的な障害が確認済みになるわけではありません。</p><button disabled={busy||!v.people.length||!operator.roles.some(r=>r==='ADMIN'||r==='OPERATOR')}>問い合わせを記録</button></form></section><h2>受け付けた問い合わせ</h2>{v.inquiries.map(x=><article key={x.event.id}><a href={`#/support/${x.event.id}`}>{x.person.displayName}さんの問い合わせ</a><p>{x.work?x.work.status==='COMPLETED'?'対応完了':x.work.workOwnerOperatorId===operator.id?'あなたの担当です':'担当者あり':'対応の必要性を未確認'}</p></article>)}</>;}
