import {useEffect,useRef,useState} from 'react';
import {api} from './api.js';
import {useRead,auditLabels,type Props} from './support-ui.js';
import type {SupportDetailView} from '../../../../packages/application/src/support-queries.js';
import {supportActionLabels,supportResultLabels,type SupportNotes,type SupportRecord} from '../../../../packages/domain/src/support.js';

const blank:SupportNotes={checks:'',action:'RESTART_GUIDANCE',actionDetails:'',result:'UNCONFIRMED',resultSource:'UNKNOWN',resultDetails:'',exceptionReason:''};
const sourceLabel={CALLER:'本人からの申告',OPERATOR:'担当者が直接確認',UNKNOWN:'未確認'};
const time=(s:string)=>new Date(s).toLocaleString('ja-JP');
function Notes({notes:n}:{notes:SupportNotes}){return <dl className="support-summary"><dt>確認したこと</dt><dd>{n.checks||'未確認'}</dd><dt>行ったこと</dt><dd>{supportActionLabels[n.action]}：{n.actionDetails||'未記入'}</dd><dt>どうなったか</dt><dd>{supportResultLabels[n.result]} / {sourceLabel[n.resultSource]}<p>{n.resultDetails}</p></dd>{n.exceptionReason&&<><dt>例外の理由</dt><dd>{n.exceptionReason}</dd></>}</dl>;}

export function SupportDetail(props:Props&{id:string}){
 const {data:v,error}=useRead<SupportDetailView>(`/api/support/${props.id}`,props.revision);
 if(error)return <p role="alert">{error}</p>;if(!v)return <p>確認しています…</p>;
 const allowed=props.operator.roles.some(r=>v.executeRoles.includes(r))&&props.operator.roles.some(r=>r==='ADMIN'||r==='OPERATOR');
 const latest=v.records.filter(x=>x.kind!=='DRAFT').at(-1);
 return <><a href="#/support">問い合わせ一覧へ</a><h1>{v.person.displayName}さんからの問い合わせ</h1><p>受付: {time(v.event.createdAt)}</p>
 <div className="workspace"><section>
 <article className="notice" aria-label="本人からの申告"><h2>本人からの申告</h2><p>{v.observation.contentText}</p><p>本人から聞いた内容です。技術的な障害として確認済みではありません。</p><details><summary>申告の出典</summary><p>{v.person.displayName} / {time(v.observation.observedAt)}</p></details></article>
 {!v.evaluation&&<section className="next-action"><h2>次にやること</h2><p>問い合わせの確認・対応を始めます。あなたの担当として記録します。</p><button disabled={props.busy||!allowed} onClick={()=>void props.run(async()=>{await api(`/api/support/${v.event.id}/evaluate`,props.csrf,{decision:'REQUIRED'});})}>対応を開始</button><details><summary>対応せずに受付を閉じる</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void props.run(async()=>{await api(`/api/support/${v.event.id}/evaluate`,props.csrf,{decision:'NOT_APPLICABLE',reason:f.get('reason')});});}}><label>対応しない理由<textarea name="reason" required maxLength={4000}/></label><button disabled={props.busy||!allowed}>理由を残して受付を閉じる</button></form></details></section>}
 {v.evaluation&&!v.work&&<article><h2>対応は作成していません</h2><p>{v.evaluation.basisSummary}</p></article>}
 {v.work&&<><section className="ownership"><p className="badge">{v.work.workOwnerOperatorId===props.operator.id?'あなたの担当です':'他の担当者の対応です'}</p><p>担当: {v.owner?.displayName??'未確認'}</p><p>担当になった理由: 対応を開始した担当者として登録されています。</p></section>
 {v.work.status!=='COMPLETED'&&<Wizard key={v.work.id} {...props} view={v} allowed={allowed}/>}
 {v.decision&&<article><h2>対応の記録</h2>{latest?<Notes notes={latest.notes}/>:<><p>確認根拠: {v.evidence?.contentText}</p><p>実施内容: {v.action?.resultSummary}</p><p>今回の判断: {v.decision.rationale}</p></>}
 <p>管理情報の変更: ありません。利用PC・VPN設定を変更した記録ではありません。</p><p>本人の申告と担当者の確認は区別して記録しています。結果の記録だけでは、VPN利用資格や恒久的な解決を確定しません。</p>
 {v.work.status!=='COMPLETED'&&<p>以前の画面で保存済みの実施記録です。上の手順で内容を編集して完了できます。元の記録は履歴に残ります。</p>}
 </article>}
 {v.work.status==='COMPLETED'&&<><p role="status">{v.work.outcome==='NO_ACTION_REQUIRED'?'調査完了・追加対応不要':'確認・案内の対応を完了しました'}</p><Correction key={`${v.work.id}-${v.records.length}`} {...props} view={v} allowed={allowed}/></>}
 {v.decision&&<details><summary>次の対応に役立つこと（任意・特になしで完了できます）</summary>{v.knowledge?<p>参考知識の候補として保存済みです。</p>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void props.run(async()=>{await api(`/api/support-work/${v.work!.id}/knowledge`,props.csrf,{title:f.get('title'),content:f.get('content')});});}}><p>必要な場合だけ残します。承認済みルールにはなりません。</p><label>参考知識の見出し<input name="title" required maxLength={200}/></label><label>役立った内容・適用条件・限界<textarea name="content" required maxLength={4000}/></label><button disabled={props.busy||!allowed}>参考知識の候補を保存</button></form>}</details>}
 </>}
 <section aria-label="過去の関連する対応"><h2>過去の関連する対応</h2><p>同じ人・同じサービスの完了した対応です。今回の原因や推奨対応を意味しません。</p>{!v.previousWork.length&&<p>該当する対応はまだありません。</p>}{v.previousWork.map(h=><article key={h.work.id}><a href={`#/support/${h.eventId}`}>{time(h.work.closedAt!)}の対応</a><p>本人の申告: {h.observation?.contentText}</p>{h.record?<Notes notes={h.record.notes}/>:<><p>行ったこと: {h.action?.resultSummary}</p><p>確認・結果の記録: {h.evidence?.contentText}</p></>}{h.record?.kind==='CORRECTION'&&<p>訂正後の記録（元の対応で履歴を確認できます）</p>}</article>)}</section>
 <details><summary>参考知識を見る</summary><p>同梱デモの参考知識。利用PCを持つことだけではVPN利用資格は分かりません。</p>{v.relatedKnowledge.map(k=><article key={k.id}><h3>{k.title}</h3><p>参考知識の候補 / 未承認 — 適用ルールではありません</p><p>{k.contentText}</p><details><summary>元の対応・確認根拠</summary><p>Work: {k.sourceWorkId}</p><p>Evidence: {k.sourceEvidenceId}</p><p>Decision: {k.sourceDecisionId}</p></details></article>)}</details>
 </section><aside aria-label="確認済みの現在の利用状況"><h2>確認済みの現在の利用状況</h2>{v.deviceFact?<div className="fact"><h3>利用PC: {v.deviceFact.device.assetTag}</h3><p>確認済み</p><p>入社PC準備で確認された利用PC情報です。再入力は不要です。</p><p>確認日時: {time(v.deviceFact.relation.verifiedAt)}</p><a href={`#/people/${v.person.id}`}>対象者の現在の利用状況</a><details><summary>利用PCの確認元</summary><a href={`#/work/${v.deviceFact.sourceChange.workId}`}>PC準備の実施・確認履歴</a><p>Relation: {v.deviceFact.relation.id}</p><p>Source Change: {v.deviceFact.relation.sourceChangeId}</p></details></div>:<p className="unknown">利用PC: 未確認。本人・端末の担当窓口に確認してください。</p>}<h3>まだ未確認の管理情報</h3><ul>{v.unknowns.map(x=><li key={x}>{x}: 未確認</li>)}</ul><p>未確認は「なし」ではありません。今回の確認記録は、この管理情報を自動で変更しません。</p></aside></div>
 <section aria-label="問い合わせの対応履歴"><h2>対応履歴</h2>{v.records.map(r=><details key={r.id}><summary>{time(r.recordedAt)} — {r.kind==='DRAFT'?'下書き保存':r.kind==='CORRECTION'?'訂正':'完了時の記録'} #{r.revision}</summary><Notes notes={r.notes}/>{r.correctionReason&&<p>訂正理由: {r.correctionReason}</p>}<p>記録者: {r.recordedByOperatorId===props.operator.id?props.operator.displayName:r.recordedByOperatorId}</p></details>)}<details><summary>監査用の詳細</summary>{v.decision&&<><p>元の確認根拠: {v.evidence?.contentText}</p><p>元の実施記録: {v.action?.resultSummary}</p><p>Evidence: {v.decision.evidenceId} / Action: {v.decision.actionId}</p></>}<ol>{v.timeline.map(e=><li key={e.id}>{time(e.occurredAt)} {auditLabels[e.eventType]??'対応記録を保存'}<pre>{JSON.stringify(e.metadataJson,null,2)}</pre></li>)}</ol></details></section>
 </>;
}

type EditorProps=Props&{view:SupportDetailView;allowed:boolean};
function useUnsaved(dirty:boolean){useEffect(()=>{if(!dirty)return;const unload=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};const leave=(e:MouseEvent)=>{if((e.target as Element).closest('a[href]')&&!window.confirm('未保存の入力があります。下書き保存せずに移動しますか？')){e.preventDefault();e.stopPropagation();}};window.addEventListener('beforeunload',unload);document.addEventListener('click',leave,true);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',leave,true);};},[dirty]);}
function Wizard({view:v,csrf,busy,run,allowed}:EditorProps){
 const [n,setN]=useState<SupportNotes>(()=>v.records.at(-1)?.notes??(v.decision?{...blank,checks:v.evidence?.contentText??'',action:v.decision.mode==='NO_ACTION_REQUIRED'?'NO_ACTION_REQUIRED':'OTHER_GUIDANCE',actionDetails:v.action?.resultSummary??'',exceptionReason:v.decision.rationale}:{...blank}));const [step,setStep]=useState(0),[dirty,setDirty]=useState(false),[message,setMessage]=useState('');
 const revision=useRef(v.records.at(-1)?.revision??0),request=useRef(crypto.randomUUID());useUnsaved(dirty);
 const change=(k:keyof SupportNotes,value:string)=>{setN(x=>({...x,[k]:value}));setDirty(true);setMessage('');request.current=crypto.randomUUID();};
 const save=(kind:'DRAFT'|'COMPLETION')=>void run(async()=>{const result=await api<SupportRecord>(`/api/support-work/${v.work!.id}/records`,csrf,{requestId:request.current,expectedRevision:revision.current,kind,notes:n,correctionReason:''});revision.current=result.revision;request.current=crypto.randomUUID();setDirty(false);setMessage(kind==='DRAFT'?'下書きを保存しました':'対応を完了しました');});
 return <section className="card support-wizard"><ol className="support-steps" aria-label="対応の手順">{['確認','対応','結果確認','完了前レビュー'].map((s,i)=><li key={s} aria-current={i===step?'step':undefined}>{i+1}. {s}</li>)}</ol><h2>次にやること</h2><h3>{['必要なことだけ確認する','実際に行ったことを記録する','どうなったかを確認する','内容を確認して完了する'][step]}</h3>
 <form onSubmit={e=>{e.preventDefault();if(step<3)setStep(step+1);else save('COMPLETION');}}><fieldset disabled={busy||!allowed}>
 {step===0&&<><p>利用PCが確認済みなら聞き直す必要はありません。VPN利用対象か、いつから・どんな表示かを、分かる範囲で確認してください。</p>{!v.deviceFact&&<p className="unknown">利用PCも未確認です。今回確認できた内容と確認元を下に残してください。</p>}<label>確認した内容と根拠<textarea value={n.checks} onChange={e=>change('checks',e.target.value)} required maxLength={1000} placeholder="例: 本人は今朝から接続できないと回答。エラー表示は未確認。利用対象は契約窓口に確認中。"/></label><p>分からない内容は未確認のままで進められます。パスワード・認証コードは記録しないでください。</p><details><summary>標準の確認手順を見る</summary><p>同梱デモ手順 / support-demo-v2。確認済みのPCは参照し、未確認の症状・利用対象を確認 → 確認・案内 → 結果を本人または担当者に確認します。実環境の承認済み手順ではありません。</p></details></>}
 {step===1&&<><p>ここでは確認・案内を記録します。機器やVPN設定の管理情報を変更する場合は、検証と正式反映を伴う別の対応が必要です。</p><label>行った対応<select aria-label="行った対応" value={n.action} onChange={e=>change('action',e.target.value)}>{Object.entries(supportActionLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>実際に行ったこと<textarea value={n.actionDetails} onChange={e=>change('actionDetails',e.target.value)} required maxLength={1000} placeholder="例: 本人にPC再起動を案内し、実施したとの回答を得た。"/></label>{['OTHER_GUIDANCE','NO_ACTION_REQUIRED'].includes(n.action)&&<label>標準外・追加対応なしの理由<textarea value={n.exceptionReason} onChange={e=>change('exceptionReason',e.target.value)} required maxLength={1000}/></label>}</>}
 {step===2&&<><label>接続の結果<select aria-label="接続の結果" value={n.result} onChange={e=>change('result',e.target.value)}>{Object.entries(supportResultLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>結果の確認元<select aria-label="結果の確認元" value={n.resultSource} onChange={e=>change('resultSource',e.target.value)}>{Object.entries(sourceLabel).map(([key,label])=><option key={key} value={key} disabled={key==='UNKNOWN'&&n.result!=='UNCONFIRMED'}>{label}</option>)}</select></label><label>結果をどう確認したか<textarea value={n.resultDetails} onChange={e=>change('resultDetails',e.target.value)} required={n.result!=='UNCONFIRMED'} maxLength={1000} placeholder="例: 本人から「再起動後に接続できた」と回答を得た。"/></label><p>本人の回答は申告として残ります。「接続できた」は恒久的な解決の認定ではありません。</p></>}
 {step===3&&<><Notes notes={n}/><p>次の対応に役立つこと: 特になし（任意のメモは完了後も追加できます）</p><p>この内容を実施記録として保存して対応を完了します。利用PCの管理情報は変わりません。</p><p>入力を直す場合は「戻る」を選んでください。</p></>}
 <div>{step>0&&<button type="button" className="secondary" onClick={()=>setStep(step-1)}>戻る</button>}<button type="button" className="secondary" onClick={()=>save('DRAFT')}>下書き保存</button><button>{step===3?'問い合わせ対応を完了':'次へ'}</button></div></fieldset></form>{message&&<p role="status">{message}</p>}</section>;
}
function Correction({view:v,csrf,busy,run,allowed}:EditorProps){
 const [open,setOpen]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState(false),[n,setN]=useState<SupportNotes>(()=>v.records.filter(x=>x.kind!=='DRAFT').at(-1)?.notes??{...blank,checks:v.evidence?.contentText??'',action:'OTHER_GUIDANCE',actionDetails:v.action?.resultSummary??''});
 const request=useRef(crypto.randomUUID());useUnsaved(open);
 const change=(k:keyof SupportNotes,value:string)=>{setN(x=>({...x,[k]:value}));request.current=crypto.randomUUID();};
 if(!open)return <button className="secondary" disabled={busy||!allowed} onClick={()=>setOpen(true)}>記録を訂正</button>;
 return <form className="card" onSubmit={e=>{e.preventDefault();if(!review){setReview(true);return;}void run(async()=>{await api(`/api/support-work/${v.work!.id}/records`,csrf,{requestId:request.current,expectedRevision:v.records.at(-1)?.revision??0,kind:'CORRECTION',notes:n,correctionReason:reason});setOpen(false);});}}><h2>完了後の訂正</h2><p>元の記録を残し、訂正者・日時・理由を追加します。作業をもう一度実行した記録にはしません。</p><fieldset disabled={busy||!allowed}>{review?<><Notes notes={n}/><p>訂正理由: {reason}</p><button type="button" className="secondary" onClick={()=>setReview(false)}>戻る</button></>:<><label>確認した内容と根拠<textarea value={n.checks} onChange={e=>change('checks',e.target.value)} maxLength={1000} required/></label><label>行った対応<select aria-label="行った対応" value={n.action} onChange={e=>change('action',e.target.value)}>{Object.entries(supportActionLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>実際に行ったこと<textarea value={n.actionDetails} onChange={e=>change('actionDetails',e.target.value)} maxLength={1000} required/></label><label>接続の結果<select aria-label="接続の結果" value={n.result} onChange={e=>change('result',e.target.value)}>{Object.entries(supportResultLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>結果の確認元<select aria-label="結果の確認元" value={n.resultSource} onChange={e=>change('resultSource',e.target.value)}>{Object.entries(sourceLabel).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>結果をどう確認したか<textarea value={n.resultDetails} onChange={e=>change('resultDetails',e.target.value)} maxLength={1000} required={n.result!=='UNCONFIRMED'}/></label>{['OTHER_GUIDANCE','NO_ACTION_REQUIRED'].includes(n.action)&&<label>標準外・追加対応なしの理由<textarea value={n.exceptionReason} onChange={e=>change('exceptionReason',e.target.value)} maxLength={1000} required/></label>}<label>訂正理由<textarea value={reason} onChange={e=>{setReason(e.target.value);request.current=crypto.randomUUID();}} required maxLength={1000}/></label></>}<button type="button" className="secondary" onClick={()=>setOpen(false)}>訂正をやめる</button><button>{review?'訂正履歴を保存':'訂正内容を確認'}</button></fieldset></form>;
}
